// Status constants
const STATUS = {
  SOLD: "sold",
  FOR_SALE: "for_sale",
  PERSONAL: "personal"
};

// Status display text
const STATUS_TEXT = {
  [STATUS.SOLD]: "Såld",
  [STATUS.FOR_SALE]: "TILL SALU",
  [STATUS.PERSONAL]: "Personlig målning – ej till salu"
};

// Shape constants
const SHAPE = {
  RECTANGULAR: "rectangular",
  CIRCLE: "circle"
};

// Medium constants
const MEDIUM = {
  ACRYLIC_CANVAS: "medium_acrylic_canvas"
};

const paintings = [
  {
    id: "herrOchFruAndersson",
    title: "Herr och Fru Andersson",
    descKey: "desc_herrOchFruAndersson",
    width: 90,
    height: 60,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 3000,
    status: STATUS.SOLD,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "womanInTheSea",
    title: "Woman of the Sea",
    descKey: "desc_womanInTheSea",
    width: 60,
    height: 90,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 2000,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "vattenfall",
    title: "Vattenfall",
    descKey: "desc_vattenfall",
    width: 33,
    height: 41,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1000,
    status: STATUS.SOLD,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "solnedgang",
    title: "Havet",
    descKey: "desc_solnedgang",
    width: 41,
    height: 33,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1000,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "solvarmeISkogen",
    title: "Solvärme i skogen",
    descKey: "desc_solvarmeISkogen",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1800,
    status: STATUS.SOLD,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "sommarstuga",
    title: "Sommarstuga",
    descKey: "desc_sommarstuga",
    width: 59,
    height: 42,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "sommarPaStranden",
    title: "Beach day",
    descKey: "desc_sommarPaStranden",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1800,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "skaViPlockaBlommor",
    title: "Näckrosor",
    descKey: "desc_skaViPlockaBlommor",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.SOLD,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "savannan",
    title: "Dags att gå hem",
    descKey: "desc_savannan",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "varkansla",
    title: "Vårkänsla",
    descKey: "desc_varkansla",
    width: 59,
    height: 42,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.SOLD,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "norrsken",
    title: "Norrsken",
    descKey: "desc_norrsken",
    width: 41,
    height: 33,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1000,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "vargen",
    title: "Två sidor av samma mynt",
    descKey: "desc_vargen",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "radjur",
    title: "Savannan",
    descKey: "desc_radjur",
    width: 90,
    height: 30,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 1500,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "skogsvila",
    title: "Skogsvila",
    descKey: "desc_skogsvila",
    diameter: 90,
    shape: SHAPE.CIRCLE,
    originalPrice: 3000,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "brollopspresent",
    title: "Bröllop",
    descKey: "desc_brollopspresent",
    width: 59,
    height: 42,
    shape: SHAPE.RECTANGULAR,
    status: STATUS.PERSONAL,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "bonnie",
    title: "Sovven och Bonnie",
    descKey: "desc_bonnie",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    status: STATUS.PERSONAL,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "vinterlek",
    title: "Vinterlek",
    descKey: "desc_vinterlek",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    status: STATUS.PERSONAL,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
  {
    id: "sommarvila",
    title: "Sommarvila",
    descKey: "desc_sommarvila",
    width: 42,
    height: 59,
    shape: SHAPE.RECTANGULAR,
    originalPrice: 2000,
    status: STATUS.FOR_SALE,
    medium: MEDIUM.ACRYLIC_CANVAS,
  },
];
